### ISSUE TITLE
Handle CSS dependencies from JS comments

### ISSUE THREAD

**Issue by rxaviers** [jquery/download.jqueryui.com#178]
As Jörn stated on https://github.com/jquery/jquery-ui/pull/1029#issuecomment-27757535, handle CSS dependencies as discussed.

> We've discussed this at the team meeting in Amsterdam. None of the solutions that load CSS through AMD are in a stage where we're willing to commit to them. In other words, specifying CSS dependencies through AMD is far from a 'solved problem', so we're not going to adopt that approach until it works.

> Since we want to share the download builder between UI and Mobile as soon as possible, we'll adopt Mobile's approach of specifying CSS dependencies in comments in JS files. We'll port the implementation from their build (or download builder). Mobile used this long enough and never ran into any major problems. Once a better solution emerges, we can delete those comments and adopt the new solution.

The jQuery Mobile download builder already [implements this](https://github.com/gseguin/node-amd-builder/blob/master/server.js#L449).

**Comment by arschmitz** [comment]
This has gone stale and i'm fairly sure the plan has changed and there are blockers here so to update about several related discussions that seem to have no documentation that have happened since.

There is a problem that came up just using @gseguin 's module as is which is that the css dependencies in the comments will map to non existent files when the widgets are pulled from ui into mobile. To fix this we need something similar to an AMD paths config. 

I believe this was discussed between @rxaviers and @gseguin in Chicago and they decided to use amd for the css under the hood but to avoid the issues previously discussed around that and forcing devs to use css dep management in their amd. The comments will stay but they will be parsed into AMD that way we can actually use a paths config to solve this just like we already do for the JS components we are pulling in. 

Related but perhaps separate is the need to separate css dependency from JS dependency. This comes up in 2 forms with the new button re-write. 

1.) Some components now depend on button CSS but not the JS like selectmenu so selecting selectmenu in the builder should pull in button CSS but not the JS.

2.) because we now support "CSS Only" buttons and controlgroups there should be a way in builder to select button css with out including the JS widget. 

ref jquery/download.jqueryui.com#246

**Comment by rxaviers** [comment]
Hi @arschmitz, yes your overall understanding is correct. We decided not to reinvent the wheel. Under the hoods, we'll transform the CSS comments into AMD definitions and let r.js handle that (via one of its css plugins) to generate the bundles (JS and CSS).

> 1.) Some components now depend on button CSS, but not the JS, like selectmenu. Selecting selectmenu in the builder should pull in button CSS but not the JS.

So, have selectmenu to define its dependency on the button css (e.g., `//>>css.structure: ../css/structure/jquery.mobile.button.css`)?

> 2.) Because we now support "CSS Only" buttons and controlgroups, there should be a way in builder, to select button css, with out including the JS widget. 

Any suggestion how this should look like?

**Comment by arschmitz** [comment]
> So, have selectmenu to define its dependency on the button css (e.g., //>>css.structure: ../css/structure/jquery.mobile.button.css)?

As long as this will support multiple comma seperated or whatever files thats fine because it would need to be like `//>>css.structure: ../css/structure/jquery.mobile.button.css, ../css/structure/jquery.mobile.selectmenu.css`

As far as how the ui would work i'm thinking the css would be its own module maybe? and the main button module would depend on the button-css module? @scottgonzalez I know we talked about this at one point and you agreed in concept that this should be possible. Don't remember if you had a suggestion on exactly how it would work though?

**Comment by rxaviers** [comment]
Yes, having multiple CSSes is possible.

**Comment by scottgonzalez** [comment]
I'd suggest an overhaul of the whole page layout. We can add a CSS Components section and rename Components to JS Components. Instead of three columns, we should have the headers full width with their descriptions. The component names and descriptions don't need so much visual spacing, they can just be thrown together with the name being bold and followed by a colon. The Theme section can probably just become part of the CSS Components section. We can probably put JS Components and CSS Components side by side in two columns to prevent the page from becoming super long.

I'm not sure what we'd do about older versions though.

**Comment by jzaefferer** [comment]
@arschmitz you said on IRC that this needs to land in 1.12. Based on the discussion here since that comment, I'm concerned that this will delay the 1.12 release, potentially quite a lot. Can you explain how this a blocker for Mobile? Are there workarounds?

**Comment by arschmitz** [comment]
@jzaefferer well part of this is required. The new ui and ability to download seperate css / js for components is NOT required. What is required is the ability to set paths for the css with a r.js config and for mobile to be able to actually use the UI download builder. These from what I understand are not far off ( unlike the new ui ).

**Comment by jzaefferer** [comment]
Okay, so let's split this into two tasks. One takes care of the underlying infrastructure, the other overhauls the user interface for custom downloads. I'd appreciate if someone else could create that second ticket, since I'm still not completely clear about the exact split.

**Comment by arschmitz** [comment]
On it!

**Comment by rxaviers** [comment]
Created https://github.com/jquery/download.jqueryui.com/issues/250
