### ISSUE TITLE
1.11.4 css download wrong

### ISSUE THREAD

**Issue by tomob7** [jquery/download.jqueryui.com#343]
Hi, when I downloaded the 1.11.4 version of a theme it didnt look right, all the elements are very thin no padding etc, also the datepicker classes in the css didnt have any 'ui-' prefixers on it.

**Comment by scottgonzalez** [comment]
I cannot reproduce missing `ui-` prefixes in the CSS.

I also cannot reproduce missing padding, etc. I assume you're just confused because the demo page is still using a font size of 62.5% because of the whacky font sizing in older themes. Just edit the body's font size on the demo page, or use the widgets for real in your own pages and they'll look just fine.

If you're continuing to have problems, please comment here with the link in the header comment of `jquery-ui.css` and we'll reopen this ticket to investigate.

**Comment by tomob7** [comment]
The download seems to be working ok now, the attached file was the wrong css that it was producing.

[jquery-ui-1.11.4.custom(2).zip](https://github.com/jquery/download.jqueryui.com/files/892498/jquery-ui-1.11.4.custom.2.zip)

**Comment by scottgonzalez** [comment]
That theme is not missing the `ui-` prefix, you added a custom prefix of `datepicker`.

**Comment by tomob7** [comment]
Ok not sure where that setting is, where do I set/remove that prefix in the builder for future reference?

**Comment by scottgonzalez** [comment]
It's the very bottom of the download page, right above the download button, labeled "CSS Scope".
